version: '2'
services:
    reporttest-app:
        image: reporttest
        external_links:
            - reporttest-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/reporttest
        ports:
            - 8080:8080
    reporttest-postgresql:
        extends:
            file: postgresql.yml
            service: reporttest-postgresql
